### ISSUE TITLE
No collection is set when using query methods

### ISSUE THREAD

**Issue by Sebastien78370** [stoussaint/spring-data-marklogic#4]
When using a specific @Repository class and doing a query method on a specific collection, the generated query does not contain any reference to the initial collection.

Given two classes A and B which both contains a Sample object which contains a sampleId. When using : 
`RepoA.findBySample_SampleId(id)`, we received a ConversionFailedException because a B result item into a A object.

When analyzing generated query, no collection was mentionned.

**Comment by stoussaint** [comment]
You are right, target collection is not set when query build from "Query Method".

**Comment by stoussaint** [comment]
Issue resolved by pull-request #5
